In [1]:
import sys

print(sys.getsizeof(10))
print(sys.getsizeof(3.14))
print(sys.getsizeof("A"))
print(sys.getsizeof([1,2,3]))

28
24
50
80


In [2]:
import numpy as np

a = np.array([5, 2, 8, 1, 3])

a.sort()

print(a)

[1 2 3 5 8]


In [3]:
import os

t = os.times()
print(t)

posix.times_result(user=1.12, system=0.17, children_user=0.0, children_system=0.0, elapsed=17183474.34)


In [5]:
import os
cores = os.cpu_count()
print(f"코어수 : {cores}")

코어수 : 6


In [6]:
import numpy as np

a = np.array([1, 2, 3])

b = a.repeat(2)

print(b)

[1 1 2 2 3 3]


In [7]:
import numpy as np

a = np.array([1, 2, 3, 4])

a.fill(0)

print(a)

[0 0 0 0]
